import './footer.css'
import { CountActive } from './ActiveClients/activeClients.js'
import { RowsPerPageClients } from './RowsPerPage/RowsPerPage.js'
import { ClientsOfPage } from './PageOf/ClientsOf.js'
import { NextPageClient } from './Pagination/nextPage.js'
const clients = [{
    name: 'israe moutawkil',
    number: 5665489891,
    description: 'katrina ipsum dolor sit amet , consecteur...',
    rate: 700.,
    currency: 'INR',
    balance: 200.00,
    deposit: 500.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'lock',
},
{
    name: 'maha ezzayer',
    number: 5665489892,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 800.00,
    currency: 'INR',
    balance: -400.00,
    deposit: 600.00,
    status: 'inactive',
    chexboxing: 'unchecked',
    checking: 'lock',

},
{
    name: 'hiba idrissi',
    number: 5665489893,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 600.00,
    currency: 'INR',
    balance: 100.00,
    deposit: 300.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',
},
{
    name: 'sara dahbi',
    number: 5665489894,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 200.00,
    currency: 'INR',
    balance: -700.00,
    deposit: 100.00,
    status: 'inactive',
    chexboxing: 'unchecked',
    checking: 'lock',
},
{

    name: 'alae idrissi',
    number: 5665489895,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 200.00,
    currency: 'INR',
    balance: 300.00,
    deposit: 300.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'lock',
},
{
    name: 'ilham janati',
    number: 5665489896,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 900.00,
    currency: 'INR',
    balance: "00.00",
    deposit: 600.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',

},
{
    name: 'mehdi benjloun',
    number: 5665489897,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 400.00,
    currency: 'INR',
    balance: -900.00,
    deposit: 600.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',

},
{
    name: 'mohamad attar',
    number: 5665489821,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 200.00,
    currency: 'INR',
    balance: 100.00,
    deposit: 600.00,
    status: 'inactive',
    chexboxing: 'unchecked',
    checking: 'notLock',
},
{
    name: 'ikram issaoui',
    number: 56654898456,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 100.00,
    currency: 'INR',
    balance: -400.00,
    deposit: 700.00,
    status: 'inactive',
    chexboxing: 'unchecked',
    checking: 'notLock',

}, {
    name: 'alae ezayed',
    number: 5665489847,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 700.00,
    currency: 'INR',
    balance: 600.00,
    deposit: 800.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'samir janati',
    number: 5665486564,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 200.00,
    currency: 'INR',
    balance: -900.00,
    deposit: 8600.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'lock',
},
{
    name: 'ismail hedad',
    number: 566548123,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 700.00,
    currency: 'INR',
    balance: 600.00,
    deposit: 300.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'lock',
}, {
    name: 'ibrahim isaoui',
    number: 56632215,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 600.00,
    currency: 'INR',
    balance: 300.00,
    deposit: 400.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'lock',
}, {
    name: 'iarim souiri',
    number: 565213288,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 500.00,
    currency: 'INR',
    balance: -6200.00,
    deposit: 300.00,
    status: 'inactive',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'younes qabaj',
    number: 13516545664,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 900.00,
    currency: 'INR',
    balance: -200.00,
    deposit: 400.00,
    status: 'inactive',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'firdaous qabaj',
    number: 53214569877,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 200.00,
    currency: 'INR',
    balance: 400.00,
    deposit: 600.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'kadin herwitz',
    number: 599875347,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 700.00,
    currency: 'INR',
    balance: -600.00,
    deposit: 800.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'abdlkrim houmidi',
    number: 588888847,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 700.00,
    currency: 'INR',
    balance: 600.00,
    deposit: 800.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'mira dokiris',
    number: 563333337,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 800.00,
    currency: 'INR',
    balance: -100.00,
    deposit: 200.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'carter Rosser',
    number: 565566677,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 400.00,
    currency: 'INR',
    balance: -300.00,
    deposit: 900.00,
    status: 'active',
    chexboxing: 'unchecked',
    checking: 'notLock',
}, {
    name: 'sanae ramzi',
    number: 56523247,
    description: 'lorem ipsum dolor sit amet, consecteur...',
    rate: 700.00,
    currency: 'INR',
    balance: 600.00,
    deposit: 800.00,
    status: 'active',
    checking: 'notLock',
    chexboxing: 'unchecked',
},

];
export const TableFooter = () => {
    return (
        <div className='footer'>
            <div className="clients" id="actived-clients">ACTIVE CUSTOMERS : <CountActive clientsToCount={clients} />
            </div>
            <RowsPerPageClients />
            <ClientsOfPage />
            <NextPageClient />
        </div>
    )
}